version: '3'
services:
  oauth-server:
    image: "gmadalon/oauth-server"
    ports:
      - "8081:8081"
    network_mode: "host"
    environment:
      - JAVA_OPTS=-Xmx200m
  restaurant-finder:
    image: "gmadalon/restaurant-finder"
    ports:
      - "8080:8080"
    network_mode: "host"
    environment:
      - JAVA_OPTS=-Xmx200m
